#!/bin/bash

# StarPU --- Runtime system for heterogeneous multicore architectures.
#
# Copyright (C) 2010  Université de Bordeaux 1
# Copyright (C) 2010, 2011  Centre National de la Recherche Scientifique
#
# StarPU is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or (at
# your option) any later version.
#
# StarPU is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU Lesser General Public License in COPYING.LGPL for more details.

./ondes3d-starpu -fixed -bsizex 256 -bsizey 256 -align -param ./DATA/aquila_1node.prm
#./ondes3d-starpu -fixed -bsizex 128 -bsizey 64 -align -param ./DATA/aquila.prm
# optirun ./ondes3d-starpu -fixed -bsizex 64 -bsizey 32 -align -param ./DATA/aquila.prm
# mpirun -n 4 ./ondes3d-starpu -fixed -bsizex 64 -bsizey 32 -align -param ./DATA/aquila.prm
